name: Deploy  Next.js MFE to Vercel

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
    inputs:
      target:
        description: 'Deploy target (preview or production)'
        required: false
        default: 'preview'
        type: choice
        options:
          - preview
          - production

jobs:
  deploy_api:
    name: Deploy API
    runs-on: ubuntu-latest
    outputs:
      api_url: ${{ steps.set_url.outputs.url }}
      api_origin: ${{ steps.set_url.outputs.origin }}
    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            api/package-lock.json
            shared/package-lock.json

      - name: Install deps (root)
        run: npm install

      - name: Install deps (shared)
        working-directory: shared
        run: npm install

      - name: Install deps (api)
        working-directory: api
        run: npm install

      - name: Install Vercel CLI
        run: npm i -g vercel@latest

      - name: Set Vercel env target (preview/production)
        id: set_env
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            if [ "${{ inputs.target }}" = "production" ]; then
              echo "VERCEL_ENV=production" >> $GITHUB_ENV
            else
              echo "VERCEL_ENV=preview" >> $GITHUB_ENV
            fi
          else
            echo "VERCEL_ENV=${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }}" >> $GITHUB_ENV
          fi

      - name: Link project (api)
        working-directory: api
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_API }}
        run: vercel link --yes --project $VERCEL_PROJECT_ID --scope=$VERCEL_ORG_ID --token=$VERCEL_TOKEN

      - name: Vercel pull (env)
        working-directory: api
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_API }}
        run: vercel pull --yes --environment=$VERCEL_ENV --token=$VERCEL_TOKEN

      - name: Build (api)
        working-directory: api
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_API }}
        run: |
          if [ "$VERCEL_ENV" = "production" ]; then
            vercel build --prod --token=$VERCEL_TOKEN
          else
            vercel build --token=$VERCEL_TOKEN
          fi

      - name: Deploy (api) - preview
        if: github.ref != 'refs/heads/main' || (github.event_name == 'workflow_dispatch' && inputs.target == 'preview')
        id: deploy_preview
        working-directory: api
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_API }}
        run: |
          set -euo pipefail
          output=$(vercel deploy --prebuilt --yes --token=$VERCEL_TOKEN | tee deployment_api_preview.log)
          url=$(echo "$output" | grep -Eo 'https://[A-Za-z0-9.-]+\.vercel\.app' | head -n 1)
          if [ -z "$url" ]; then
            echo "Failed to parse preview deployment URL from Vercel output" >&2
            exit 1
          fi
          echo "url=$url" >> $GITHUB_OUTPUT

      - name: Deploy (api) - production
        if: github.ref == 'refs/heads/main' || (github.event_name == 'workflow_dispatch' && inputs.target == 'production')
        id: deploy_prod
        working-directory: api
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_API }}
        run: |
          set -euo pipefail
          output=$(vercel deploy --prebuilt --prod --yes --token=$VERCEL_TOKEN | tee deployment_api.log)
          url=$(echo "$output" | grep -Eo 'https://[A-Za-z0-9.-]+\.vercel\.app' | head -n 1)
          if [ -z "$url" ]; then
            echo "Failed to parse deployment URL from Vercel output" >&2
            exit 1
          fi
          echo "url=$url" >> $GITHUB_OUTPUT

      - name: Set URL output
        id: set_url
        run: |
          raw_url="${{ steps.deploy_preview.outputs.url || steps.deploy_prod.outputs.url }}"
          if [ -z "$raw_url" ]; then
            echo "Failed to determine deployment URL" >&2
            exit 1
          fi

          # Remove trailing slashes for consistency
          trimmed="${raw_url%/}"
          origin="${trimmed:-$raw_url}"

          echo "origin=$origin" >> $GITHUB_OUTPUT
          echo "url=${origin}/api" >> $GITHUB_OUTPUT

  deploy_home:
    name: Deploy Home
    needs: deploy_api
    runs-on: ubuntu-latest
    outputs:
      home_url: ${{ steps.set_url.outputs.url }}
    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            home/package-lock.json
            shared/package-lock.json

      - name: Install deps (root)
        run: npm install

      - name: Install deps (shared)
        working-directory: shared
        run: npm install

      - name: Install deps (home)
        working-directory: home
        run: npm install

      - name: Install Vercel CLI
        run: npm i -g vercel@latest

      - name: Set Vercel env target (preview/production)
        id: set_env
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            if [ "${{ inputs.target }}" = "production" ]; then
              echo "VERCEL_ENV=production" >> $GITHUB_ENV
            else
              echo "VERCEL_ENV=preview" >> $GITHUB_ENV
            fi
          else
            echo "VERCEL_ENV=${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }}" >> $GITHUB_ENV
          fi

      - name: Select API URL for home
        run: |
          normalize_api_url() {
            local url="$1"
            if [ -z "$url" ]; then
              echo "API URL cannot be empty" >&2
              exit 1
            fi

            # Strip trailing slashes
            while [ "${url%/}" != "$url" ]; do
              url="${url%/}"
            done

            case "$url" in
              */api) ;;
              *) url="${url}/api" ;;
            esac

            printf '%s\n' "$url"
          }

          if [ "$VERCEL_ENV" = "production" ]; then
            echo "NEXT_PUBLIC_API_URL=$(normalize_api_url '${{ secrets.PROD_API_URL }}')" >> $GITHUB_ENV
          else
            echo "NEXT_PUBLIC_API_URL=$(normalize_api_url '${{ needs.deploy_api.outputs.api_url }}')" >> $GITHUB_ENV
          fi

      - name: Link project (home)
        working-directory: home
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_HOME }}
        run: vercel link --yes --project $VERCEL_PROJECT_ID --scope=$VERCEL_ORG_ID --token=$VERCEL_TOKEN

      - name: Vercel pull (env)
        working-directory: home
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_HOME }}
        run: vercel pull --yes --environment=$VERCEL_ENV --token=$VERCEL_TOKEN

      - name: Build (home)
        working-directory: home
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_HOME }}
          NEXT_PUBLIC_API_URL: ${{ env.NEXT_PUBLIC_API_URL }}
        run: |
          if [ "$VERCEL_ENV" = "production" ]; then
            vercel build --prod --token=$VERCEL_TOKEN
          else
            vercel build --token=$VERCEL_TOKEN
          fi

      - name: Deploy (home) - preview
        if: github.ref != 'refs/heads/main' || (github.event_name == 'workflow_dispatch' && inputs.target == 'preview')
        id: deploy_preview
        working-directory: home
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_HOME }}
        run: |
          set -euo pipefail
          output=$(vercel deploy --prebuilt --yes --token=$VERCEL_TOKEN | tee deployment_home_preview.log)
          url=$(echo "$output" | grep -Eo 'https://[A-Za-z0-9.-]+\.vercel\.app' | head -n 1)
          if [ -z "$url" ]; then
            echo "Failed to parse preview deployment URL from Vercel output" >&2
            exit 1
          fi
          echo "url=$url" >> $GITHUB_OUTPUT

      - name: Deploy (home) - production
        if: github.ref == 'refs/heads/main' || (github.event_name == 'workflow_dispatch' && inputs.target == 'production')
        id: deploy_prod
        working-directory: home
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_HOME }}
        run: |
          set -euo pipefail
          output=$(vercel deploy --prebuilt --prod --yes --token=$VERCEL_TOKEN | tee deployment_home.log)
          url=$(echo "$output" | grep -Eo 'https://[A-Za-z0-9.-]+\.vercel\.app' | head -n 1)
          if [ -z "$url" ]; then
            echo "Failed to parse deployment URL from Vercel output" >&2
            exit 1
          fi
          echo "url=$url" >> $GITHUB_OUTPUT

      - name: Set URL output
        id: set_url
        run: echo "url=${{ steps.deploy_preview.outputs.url || steps.deploy_prod.outputs.url }}" >> $GITHUB_OUTPUT

  deploy_login:
    name: Deploy Login
    runs-on: ubuntu-latest
    needs:
      - deploy_home
      - deploy_api
    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            login/package-lock.json
            shared/package-lock.json

      - name: Install deps (root)
        run: npm install

      - name: Install deps (shared)
        working-directory: shared
        run: npm install

      - name: Install deps (login)
        working-directory: login
        run: npm install

      - name: Install Vercel CLI
        run: npm i -g vercel@latest

      - name: Set Vercel env target (preview/production)
        id: set_env
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            if [ "${{ inputs.target }}" = "production" ]; then
              echo "VERCEL_ENV=production" >> $GITHUB_ENV
            else
              echo "VERCEL_ENV=preview" >> $GITHUB_ENV
            fi
          else
            echo "VERCEL_ENV=${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }}" >> $GITHUB_ENV
          fi

      - name: Select HOME_URL for login
        run: |
          if [ "$VERCEL_ENV" = "production" ]; then
            # Use stable default domain for Home in production (set this secret to e.g. https://mfe-tech-challenge-cfqw.vercel.app)
            echo "HOME_URL=${{ secrets.PROD_HOME_URL }}" >> $GITHUB_ENV
          else
            # Use freshly deployed Home preview URL
            echo "HOME_URL=${{ needs.deploy_home.outputs.home_url }}" >> $GITHUB_ENV
          fi

      - name: Select API URL for login
        run: |
          normalize_api_url() {
            local url="$1"
            if [ -z "$url" ]; then
              echo "API URL cannot be empty" >&2
              exit 1
            fi

            while [ "${url%/}" != "$url" ]; do
              url="${url%/}"
            done

            case "$url" in
              */api) ;;
              *) url="${url}/api" ;;
            esac

            printf '%s\n' "$url"
          }

          if [ "$VERCEL_ENV" = "production" ]; then
            echo "NEXT_PUBLIC_API_URL=$(normalize_api_url '${{ secrets.PROD_API_URL }}')" >> $GITHUB_ENV
          else
            echo "NEXT_PUBLIC_API_URL=$(normalize_api_url '${{ needs.deploy_api.outputs.api_url }}')" >> $GITHUB_ENV
          fi

      - name: Link project (login)
        working-directory: login
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_LOGIN }}
        run: vercel link --yes --project $VERCEL_PROJECT_ID --scope=$VERCEL_ORG_ID --token=$VERCEL_TOKEN

      - name: Vercel pull (env)
        working-directory: login
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_LOGIN }}
        run: vercel pull --yes --environment=$VERCEL_ENV --token=$VERCEL_TOKEN

      - name: Build (login)
        working-directory: login
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_LOGIN }}
          NEXT_PUBLIC_HOME_URL: ${{ env.HOME_URL }}
          NEXT_PUBLIC_API_URL: ${{ env.NEXT_PUBLIC_API_URL }}
        run: |
          if [ "$VERCEL_ENV" = "production" ]; then
            vercel build --prod --token=$VERCEL_TOKEN
          else
            vercel build --token=$VERCEL_TOKEN
          fi

      - name: Deploy (login) - preview
        if: github.ref != 'refs/heads/main' || (github.event_name == 'workflow_dispatch' && inputs.target == 'preview')
        working-directory: login
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_LOGIN }}
        run: vercel deploy --prebuilt --yes --token=$VERCEL_TOKEN

      - name: Deploy (login) - production
        if: github.ref == 'refs/heads/main' || (github.event_name == 'workflow_dispatch' && inputs.target == 'production')
        working-directory: login
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_LOGIN }}
        run: vercel deploy --prebuilt --prod --yes --token=$VERCEL_TOKEN
