name: Deploy  Next.js MFE to Vercel

on:
  push:
    branches: [main]
  pull_request:

jobs:
  deploy_home:
    name: Deploy Home
    runs-on: ubuntu-latest
    outputs:
      home_url: ${{ steps.set_url.outputs.url }}
    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: home/package-lock.json

      - name: Install deps (home)
        working-directory: home
        run: npm install

      - name: Install Vercel CLI
        run: npm i -g vercel@latest

      - name: Set Vercel env target (preview/production)
        id: set_env
        run: echo "VERCEL_ENV=${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }}" >> $GITHUB_ENV

      - name: Vercel pull (env)
        working-directory: home
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_HOME }}
        run: vercel pull --yes --environment=$VERCEL_ENV

      - name: Build (home)
        working-directory: home
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_HOME }}
        run: vercel build

      - name: Deploy (home) - production
        if: github.ref == 'refs/heads/main'
        id: deploy_prod
        working-directory: home
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_HOME }}
        run: |
          output=$(vercel deploy --prebuilt --prod --yes --json)
          echo "$output" | tee deployment_home.json
          url=$(jq -r '.url' deployment_home.json)
          echo "url=https://$url" >> $GITHUB_OUTPUT

      - name: Set URL output
        id: set_url
        run: echo "url=${{ steps.deploy_preview.outputs.url || steps.deploy_prod.outputs.url }}" >> $GITHUB_OUTPUT

  deploy_login:
    name: Deploy Login
    runs-on: ubuntu-latest
    needs: deploy_home
    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: login/package-lock.json

      - name: Install deps (login)
        working-directory: login
        run: npm install

      - name: Install Vercel CLI
        run: npm i -g vercel@latest

      - name: Set Vercel env target (preview/production)
        id: set_env
        run: echo "VERCEL_ENV=${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }}" >> $GITHUB_ENV

      - name: Vercel pull (env)
        working-directory: login
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_LOGIN }}
        run: vercel pull --yes --environment=$VERCEL_ENV

      - name: Build (login)
        working-directory: login
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_LOGIN }}
          NEXT_PUBLIC_HOME_URL: ${{ needs.deploy_home.outputs.home_url }}
        run: vercel build

      - name: Deploy (login) - production
        if: github.ref == 'refs/heads/main'
        working-directory: login
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_LOGIN }}
        run: vercel deploy --prebuilt --prod --yes
